/* Reset styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

/* Body styles */
body {
  font-family: Arial, sans-serif;
  background-color: #121212;
  color: #fff;
}

/* Header styles */
header {
  background-color: #333;
  padding: 20px;
}

nav ul {
  list-style: none;
  padding: 0;
}

nav ul li {
  display: inline;
  margin-right: 20px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

/* Hero section styles */
.hero {
  background-color: #1a1a1a;
  padding: 100px 20px;
  text-align: center;
}

.hero-content h1 {
  font-size: 3em;
  margin-bottom: 20px;
}

.hero-content p {
  font-size: 1.2em;
}

/* About, Portfolio, Contact section styles */
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

section h2 {
  margin-bottom: 20px;
}

.gallery {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
}

.gallery img {
  max-width: 100%;
  height: auto;
}

/* Footer styles */
footer {
  background-color: #333;
  padding: 20px;
  text-align: center;
}

footer p {
  font-size: 0.8em;
}

